/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITest_display
  (JNIEnv *, jclass);

/*
 * Class:     JNITest
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNITest_increment
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
